### ISSUE TITLE
rotate() 중 에러가 발생합니다! 

### ISSUE THREAD

**Issue by juijeong8324** [SE10team/Tetris_final#4]
![image](https://user-images.githubusercontent.com/63052097/161965983-7a5ab7e5-c518-45d3-ad99-127e6009f16e.png)
화면을 보시면 빈 공간에 해당 블록을 rotate()를 했는데 블록이 화면 밖을 벗어나면서 에러가 뜨고 중지 됩니다!!
이를 어떻게 해결하면 좋을까요? 
![image](https://user-images.githubusercontent.com/63052097/161966151-98a2fe55-760e-412f-ac5d-0a6ceb1907ca.png)

**Comment by shinyubin989** [comment]
음~음~~~~~~~~~~~~~~~~~~~치킨

**Comment by yoon-H** [comment]
rotate 되는 범위를 비교해서 회전 가능 여부를 가늠할 수 있게 만들었습니다!😁
